### ISSUE TITLE
RIAK client timeout error

### ISSUE THREAD

**Issue by NetMango** [basho/riak-phppb-client#3] opened 2016-05-25 18:01 UTC
Hi.

I'm in trouble. I asked a question, but still no reply: http://stackoverflow.com/questions/37437021/riak-php-client-timeout-error

Can you help me? Thank you.

**Comment by lukebakken** [comment] 2016-05-25 18:10
Hello -

We are going to need more details to be able to help:
- Can you please provide all of your code as well as configuration for PHP and `nginx`?
- How many Riak nodes are you using? Can you run `riak-debug` on one node and provide the generated archive?

Ideally, we should be able to set up an environment like yours and reproduce the issue. Having the exact code and configuration you are using will speed that process up.

**Comment by christophermancini** [comment] 2016-05-25 18:12
Also, if you can configure logging for PHP-FPM and reproduce the issue, those logs will be very useful in determining if the issue is within our library or how the library is being used. Thanks.

**Comment by NetMango** [comment] 2016-05-25 19:14
Hello Guys.

I'm using only 1 node at host. Now it's just for a PHP test. ( look at in attachment RiakObjectStorage.class.php file )

My OS is Ubuntu 14.04LTS 64bit

NGINX ( with passanger ) is installed by this few commands:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
- sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main > /etc/apt/sources.list.d/passenger.list'
- sudo apt-get update
- sudo apt-get install -y nginx-extras passenger

Every configs and settings are in the attachment, but php-fpm config is default for example. And no one error exists in php-fpm log, just a few 

> [_25-May-2016 19:57:45] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful

 lines.

I really belive that something wrong at my side, becouse when this error appears, i can't run no one other php code at my host, all of them throws connection time out.

And I have 2 RIAK production cluster ( each with 3 nodes ) at other environment, but there i use JAVA client with JAVA EE7 and i never met such error. So this is really strange for me.

Sorry for my bad english, thank you for your help. 

[riak.tar.gz](https://github.com/basho/riak-phppb-client/files/282700/riak.tar.gz)

**Comment by christophermancini** [comment] 2016-05-26 12:26
Lets reduce the amount of hands in the process, what happens when you run it via CLI instead of through Nginx?

**Comment by NetMango** [comment] 2016-05-26 12:41
Hi.

PHP Fatal error:  Class 'ProtobufMessage' not found in /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak-pb/src/Riak/Api/Pb/Message/RpbGetReq.php on line 13

**Comment by christophermancini** [comment] 2016-05-26 12:42
Have you added the protobuf.so extension to the php.ini for your CLI command? You can check by doing `php -m | grep proto`

**Comment by NetMango** [comment] 2016-05-26 12:49
Ohh sorry, in cli not. But now I did it. New log:

PHP Warning:  stream_socket_client(): unable to connect to tcp://flowtion.sytes.net:8087 (Connection timed out) in /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak-pb/src/Riak/Api/Pb.php on line 644
PHP Fatal error:  Uncaught exception 'Basho\Riak\Api\Exception' with message '110 - Connection timed out' in /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak-pb/src/Riak/Api/Pb.php:646
Stack trace:
#0 /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak-pb/src/Riak/Api/Pb.php(62): Basho\Riak\Api\Pb->openConnection()
#1 /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak/src/Riak/Node.php(206): Basho\Riak\Api\Pb->prepare(Object(Basho\Riak\Command\Object\Fetch), Object(Basho\Riak\Node))
#2 /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak/src/Riak.php(163): Basho\Riak\Node->execute(Object(Basho\Riak\Command\Object\Fetch), Object(Basho\Riak\Api\Pb))
#3 /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak/src/Riak/Command.php(68): Basho\Riak->execute(Object(Basho\Riak\Command\Object\Fetch))
#4 /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak/src/Riak/Command/Object.php(77): Basho\Riak\Command->execute()
#5 /home/netmango/www/flowtion/BIBacken in /home/netmango/www/flowtion/BIBackend/BashoRiak/vendor/basho/riak-pb/src/Riak/Api/Pb.php on line 646

**Comment by NetMango** [comment] 2016-05-26 13:01
OOOOOOOHHHH, maybe this is a problem:

I tried:

```
nmap -p 8087 flowtion.sytes.net

Starting Nmap 6.40 ( http://nmap.org ) at 2016-05-26 14:54 CEST
Nmap scan report for flowtion.sytes.net (204.11.56.50)
Host is up (0.18s latency).
PORT     STATE    SERVICE
8087/tcp filtered simplifymedia
```

What??? I don't filter anything.... let's try:

```
nmap -p 8087 46.139.101.83

Starting Nmap 6.40 ( http://nmap.org ) at 2016-05-26 14:55 CEST
Nmap scan report for 2E8B6553.catv.pool.telekom.hu (46.139.101.83)
Host is up (0.037s latency).
PORT     STATE SERVICE
8087/tcp open  simplifymedia
```

A bit better :+1: 

But who filters the domain? Maybe noip? It's a noip host :(

And changed hostname to IP and it runs 10/10. AAAIIIGHHH slowly i go crazy!

**Comment by NetMango** [comment] 2016-05-26 13:02
I test is for a while and i tell you still has error...

**Comment by christophermancini** [comment] 2016-05-26 13:05
Can you run Riak locally to test your code?

**Comment by NetMango** [comment] 2016-05-26 13:06
NO, no error... everything is ok. I tried 1000 times.

So guys... really sorry for disturbing you. Don't be angry for me. My problem solved. And really thank you for your guide. :+1:

**Comment by christophermancini** [comment] 2016-05-26 13:07
Great, glad you got it figured out! No worries about disturbing us. :)

**Comment by NetMango** [comment] 2016-05-26 13:07
Thank you so much :)

**Comment by NetMango** [comment] 2016-05-26 16:01
Guys, really sorry but the error appeared again with IP address, just i had to wait some time... :(

But I can say, when php5-fpm fails, php cli is always good, it always works!!! This is the main difference. But I can't  extort any debug or error log from php5-fpm.

**Comment by lukebakken** [comment] 2016-05-26 19:09
I am assuming that if the PHP cli works, then the issue is most likely _not_ with `riak-phppb-client`, but your environment. Can you try using a different FCGI implementation or web server?

**Comment by NetMango** [comment] 2016-05-26 19:25
Yes, it's clear, there is a problem with php-fpm. BUT!
We always use NGINX since years for many reasons, and it comes with php-fpm. I really don't know other FCGI. And this configuration widely used, not only by me.  
But i'll test it on other servers with NGINX php-fpm combo, and we'll see. If my environment is not the only one which fails ( i never had such problem before ) , it should be a really environment specific bug.

**Comment by christophermancini** [comment] 2016-05-26 19:27
@NetMango You should look at the following docs to help determine where your config issue is. I would first start with getting PHP-FPM to output the errors experienced by the workers.

http://php.net/manual/en/install.fpm.configuration.php
http://stackoverflow.com/questions/8677493/php-fpm-doesnt-write-to-error-log

**Comment by NetMango** [comment] 2016-05-30 09:14
Hi.

I've read all docs, made all settings but i was unable to get more informations from log. Only log was the known timeout log. And i had to realize if i run my code on different server the result is the same: cli always worked well, but php-fpm failed frequently. You know i had to give it up, because my time was running out, i had to finish my project to certain time. 

So i picked my well established wildfly server and my JAVA code, what is running on more environments about 6 mouths. Started a test environment and it's working always perfectly as i expected. 

I was unable to get to the bottom of this issue, probably i will have time in the future. 
Please keep in mind this issue. 

Thak you for your patience.

**Comment by christophermancini** [comment] 2016-05-30 14:59
Ok, for now, I am going to close this issue. Feel free to reopen should you have issues going forward.

**Closed as completed by christophermancini** 2016-05-30 14:59 UTC
